[package]
name = "omlc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
gloo = "0.10.0"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"
yew = { version = "0.21.0", features = ["csr"] }
